name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-rel-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-rel-
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-release-
      - name: Build project
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: makao-online-${{ runner.os }}
          path: ./target/release/makao-online*
      - name: Run tests
        run: cargo test --verbose
      - name: Run linter
        if: runner.os != 'macOS'
        run: cargo clippy -- -D warnings

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: makao-online-${{ runner.os }}
          path: ./target/
      - name: Clean .d file
        working-directory: ./target/
        run: |
          rm makao-online.d
      - name: Rename macOS artifact
        if: runner.os == 'macOS'
        working-directory: ./target/
        run: |
          mv makao-online makao-online-macos
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./target/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
